# Copyright 2021 Matt Moore
# SPDX-License-Identifier: Apache-2.0

name: Github Test

on:
  push:
    branches: [ '*' ]

  pull_request:
    branches: [ 'main', 'master', 'release-*', 'mkdocs' ]

jobs:

  with-permissions:
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write  # undocumented OIDC support.
      contents: read

    name: Actions with permissions
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: v1.16.x

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run: |
          go install .

          oidc-magic

  without-permissions:
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    # permissions:
    #   id-token: write  # undocumented OIDC support.

    name: Actions without permissions
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: v1.16.x

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run: |
          go install .

          oidc-magic
